SRCS=\
 ../../UI/Console/ConsoleClose.cpp \
 ../../UI/Console/ExtractCallbackConsole.cpp \
 ../../UI/Console/List.cpp \
 ../../UI/Console/Main.cpp \
 ../../UI/Console/MainAr.cpp \
 ../../UI/Console/OpenCallbackConsole.cpp \
 ../../UI/Console/PercentPrinter.cpp \
 ../../UI/Console/UpdateCallbackConsole.cpp \
 ../../UI/Console/UserInputUtils.cpp \
 ../../Archive/7z/7zCompressionMode.cpp \
 ../../Archive/7z/7zDecode.cpp \
 ../../Archive/7z/7zEncode.cpp \
 ../../Archive/7z/7zExtract.cpp \
 ../../Archive/7z/7zFolderInStream.cpp \
 ../../Archive/7z/7zFolderOutStream.cpp \
 ../../Archive/7z/7zHandler.cpp \
 ../../Archive/7z/7zHandlerOut.cpp \
 ../../Archive/7z/7zHeader.cpp \
 ../../Archive/7z/7zIn.cpp \
 ../../Archive/7z/7zMethodID.cpp \
 ../../Archive/7z/7zOut.cpp \
 ../../Archive/7z/7zProperties.cpp \
 ../../Archive/7z/7zSpecStream.cpp \
 ../../Archive/7z/7zUpdate.cpp \
 ../../Archive/Common/CoderMixer2.cpp \
 ../../Archive/Common/CoderMixer2MT.cpp \
 ../../Archive/Common/CrossThreadProgress.cpp \
 ../../Archive/Common/DummyOutStream.cpp \
 ../../Archive/Common/FilterCoder.cpp \
 ../../Archive/Common/InStreamWithCRC.cpp \
 ../../Archive/Common/ItemNameUtils.cpp \
 ../../Archive/Common/MultiStream.cpp \
 ../../Archive/Common/OutStreamWithCRC.cpp \
 ../../Archive/Common/ParseProperties.cpp \
 ../../Common/FilePathAutoRename.cpp \
 ../../Common/FileStreams.cpp \
 ../../Common/InBuffer.cpp \
 ../../Common/InOutTempBuffer.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/LockedStream.cpp \
 ../../Common/OffsetStream.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamBinder.cpp \
 ../../Common/StreamObjects.cpp \
 ../../Compress/Branch/BranchCoder.cpp \
 ../../Compress/Branch/x86_2.cpp \
 ../../Compress/Branch/x86.cpp \
 ../../Compress/Copy/CopyCoder.cpp \
 ../../Compress/LZ/LZInWindow.cpp \
 ../../Compress/LZ/LZOutWindow.cpp \
 ../../Compress/LZMA/LZMADecoder.cpp \
 ../../Compress/LZMA/LZMAEncoder.cpp \
 ../../Compress/LZ/MT/MT.cpp \
 ../../Compress/RangeCoder/RangeCoderBit.cpp \
 ../../UI/Common/ArchiveCommandLine.cpp \
 ../../UI/Common/ArchiveExtractCallback.cpp \
 ../../UI/Common/ArchiveOpenCallback.cpp \
 ../../UI/Common/ArchiverInfo.cpp \
 ../../UI/Common/DefaultName.cpp \
 ../../UI/Common/EnumDirItems.cpp \
 ../../UI/Common/Extract.cpp \
 ../../UI/Common/ExtractingFilePath.cpp \
 ../../UI/Common/OpenArchive.cpp \
 ../../UI/Common/PropIDUtils.cpp \
 ../../UI/Common/SetProperties.cpp \
 ../../UI/Common/SortUtils.cpp \
 ../../UI/Common/TempFiles.cpp \
 ../../UI/Common/UpdateAction.cpp \
 ../../UI/Common/UpdateCallback.cpp \
 ../../UI/Common/Update.cpp \
 ../../UI/Common/UpdatePair.cpp \
 ../../UI/Common/UpdateProduce.cpp \
 ../../../Windows/Error.cpp \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/FileName.cpp \
 ../../../Windows/PropVariantConversions.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/Synchronization.cpp

ConsoleClose.o : ../../UI/Console/ConsoleClose.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/ConsoleClose.cpp
ExtractCallbackConsole.o : ../../UI/Console/ExtractCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/ExtractCallbackConsole.cpp
List.o : ../../UI/Console/List.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/List.cpp
Main.o : ../../UI/Console/Main.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/Main.cpp
MainAr.o : ../../UI/Console/MainAr.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/MainAr.cpp
OpenCallbackConsole.o : ../../UI/Console/OpenCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/OpenCallbackConsole.cpp
PercentPrinter.o : ../../UI/Console/PercentPrinter.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/PercentPrinter.cpp
UpdateCallbackConsole.o : ../../UI/Console/UpdateCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/UpdateCallbackConsole.cpp
UserInputUtils.o : ../../UI/Console/UserInputUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/UserInputUtils.cpp










Error.o : ../../../Windows/Error.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Error.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariantConversions.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
CrossThreadProgress.o : ../../Archive/Common/CrossThreadProgress.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CrossThreadProgress.cpp
FilePathAutoRename.o : ../../Common/FilePathAutoRename.cpp
	$(CXX) $(CFLAGS) ../../Common/FilePathAutoRename.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/FileStreams.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
InOutTempBuffer.o : ../../Common/InOutTempBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InOutTempBuffer.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
LockedStream.o : ../../Common/LockedStream.cpp
	$(CXX) $(CFLAGS) ../../Common/LockedStream.cpp
OffsetStream.o : ../../Common/OffsetStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OffsetStream.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamBinder.o : ../../Common/StreamBinder.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamBinder.cpp
StreamObjects.o : ../../Common/StreamObjects.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamObjects.cpp
BranchCoder.o : ../../Compress/Branch/BranchCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BranchCoder.cpp
x86.o : ../../Compress/Branch/x86.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86.cpp
x86_2.o : ../../Compress/Branch/x86_2.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86_2.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
MT.o : ../../Compress/LZ/MT/MT.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/MT/MT.cpp
LZInWindow.o : ../../Compress/LZ/LZInWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZInWindow.cpp
LZOutWindow.o : ../../Compress/LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZOutWindow.cpp
LZMADecoder.o : ../../Compress/LZMA/LZMADecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMADecoder.cpp
LZMAEncoder.o : ../../Compress/LZMA/LZMAEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMAEncoder.cpp
RangeCoderBit.o : ../../Compress/RangeCoder/RangeCoderBit.cpp
	$(CXX) $(CFLAGS) ../../Compress/RangeCoder/RangeCoderBit.cpp
7zCompressionMode.o : ../../Archive/7z/7zCompressionMode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zCompressionMode.cpp
7zDecode.o : ../../Archive/7z/7zDecode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zDecode.cpp
7zEncode.o : ../../Archive/7z/7zEncode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zEncode.cpp
7zExtract.o : ../../Archive/7z/7zExtract.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zExtract.cpp
7zFolderInStream.o : ../../Archive/7z/7zFolderInStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderInStream.cpp
7zFolderOutStream.o : ../../Archive/7z/7zFolderOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderOutStream.cpp
7zHandler.o : ../../Archive/7z/7zHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandler.cpp
7zHandlerOut.o : ../../Archive/7z/7zHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandlerOut.cpp
7zHeader.o : ../../Archive/7z/7zHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHeader.cpp
7zIn.o : ../../Archive/7z/7zIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zIn.cpp
7zMethodID.o : ../../Archive/7z/7zMethodID.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zMethodID.cpp
7zOut.o : ../../Archive/7z/7zOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zOut.cpp
7zProperties.o : ../../Archive/7z/7zProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zProperties.cpp
7zSpecStream.o : ../../Archive/7z/7zSpecStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zSpecStream.cpp
7zUpdate.o : ../../Archive/7z/7zUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zUpdate.cpp
CoderMixer2.o : ../../Archive/Common/CoderMixer2.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2.cpp
CoderMixer2MT.o : ../../Archive/Common/CoderMixer2MT.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2MT.cpp
DummyOutStream.o : ../../Archive/Common/DummyOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/DummyOutStream.cpp
FilterCoder.o : ../../Archive/Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/FilterCoder.cpp
InStreamWithCRC.o : ../../Archive/Common/InStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/InStreamWithCRC.cpp
ItemNameUtils.o : ../../Archive/Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ItemNameUtils.cpp
OutStreamWithCRC.o : ../../Archive/Common/OutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/OutStreamWithCRC.cpp
ParseProperties.o : ../../Archive/Common/ParseProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ParseProperties.cpp
MultiStream.o : ../../Archive/Common/MultiStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/MultiStream.cpp
ArchiveCommandLine.o : ../../UI/Common/ArchiveCommandLine.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveCommandLine.cpp
ArchiveExtractCallback.o : ../../UI/Common/ArchiveExtractCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveExtractCallback.cpp
ArchiveOpenCallback.o : ../../UI/Common/ArchiveOpenCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveOpenCallback.cpp
ArchiverInfo.o : ../../UI/Common/ArchiverInfo.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiverInfo.cpp
DefaultName.o : ../../UI/Common/DefaultName.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/DefaultName.cpp
EnumDirItems.o : ../../UI/Common/EnumDirItems.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/EnumDirItems.cpp
Extract.o : ../../UI/Common/Extract.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/Extract.cpp
SetProperties.o : ../../UI/Common/SetProperties.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/SetProperties.cpp
ExtractingFilePath.o : ../../UI/Common/ExtractingFilePath.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ExtractingFilePath.cpp
OpenArchive.o : ../../UI/Common/OpenArchive.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/OpenArchive.cpp
PropIDUtils.o : ../../UI/Common/PropIDUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/PropIDUtils.cpp
SortUtils.o : ../../UI/Common/SortUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/SortUtils.cpp
TempFiles.o : ../../UI/Common/TempFiles.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/TempFiles.cpp
Update.o : ../../UI/Common/Update.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/Update.cpp
UpdateAction.o : ../../UI/Common/UpdateAction.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdateAction.cpp
UpdateCallback.o : ../../UI/Common/UpdateCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdateCallback.cpp
UpdatePair.o : ../../UI/Common/UpdatePair.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdatePair.cpp
UpdateProduce.o : ../../UI/Common/UpdateProduce.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdateProduce.cpp
