PROG=../../../bin/Codecs/AES.so

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

OBJS = \
../../../Common/MyWindows.o \
DllExports.o\
MyAES.o\
aescrypt.o\
aeskey.o\
aestab.o

include ../../../makefile.glb

