SRCS=\
../../Archive/7z/DllExports.cpp \
../../../Common/Alloc.cpp \
../../../Common/CRC.cpp \
../../../Common/IntToString.cpp \
../../../Common/String.cpp \
../../../Common/StringConvert.cpp \
../../../Common/StringToInt.cpp \
../../../Common/Vector.cpp \
../../../Common/Wildcard.cpp \
../../../Windows/FileDir.cpp \
../../../Windows/FileFind.cpp \
../../../Windows/FileIO.cpp \
../../../Windows/PropVariant.cpp \
../../../Windows/Synchronization.cpp \
../../Archive/Common/CoderMixer2.cpp \
../../Archive/Common/CoderMixer2MT.cpp \
../../Archive/Common/CrossThreadProgress.cpp \
../../Archive/Common/FilterCoder.cpp \
../../Archive/Common/InStreamWithCRC.cpp \
../../Archive/Common/ItemNameUtils.cpp \
../../Archive/Common/OutStreamWithCRC.cpp \
../../Archive/Common/ParseProperties.cpp \
../../Compress/LZ/MT/MT.cpp \
../../Compress/LZ/LZInWindow.cpp \
../../Compress/LZ/LZOutWindow.cpp \
../../Compress/PPMD/PPMDDecoder.cpp \
../../Compress/PPMD/PPMDEncoder.cpp \
../../Compress/Branch/BranchCoder.cpp \
../../Compress/Branch/x86.cpp \
../../Compress/Branch/x86_2.cpp \
../../Compress/LZMA/LZMADecoder.cpp \
../../Compress/LZMA/LZMAEncoder.cpp \
../../Compress/Copy/CopyCoder.cpp \
../../Compress/RangeCoder/RangeCoderBit.cpp \
../../Compress/Deflate/DeflateDecoder.cpp \
../../Compress/BZip2/BZip2CRC.cpp \
../../Compress/BZip2/BZip2Decoder.cpp \
../../Crypto/AES/MyAES.cpp \
../../Crypto/7zAES/7zAES.cpp \
../../Crypto/Hash/Sha256.cpp \
../../Archive/7z/7zDecode.cpp \
../../Archive/7z/7zEncode.cpp \
../../Archive/7z/7zExtract.cpp \
../../Archive/7z/7zFolderInStream.cpp \
../../Archive/7z/7zFolderOutStream.cpp \
../../Archive/7z/7zHandler.cpp \
../../Archive/7z/7zHandlerOut.cpp \
../../Archive/7z/7zHeader.cpp \
../../Archive/7z/7zIn.cpp \
../../Archive/7z/7zMethodID.cpp \
../../Archive/7z/7zOut.cpp \
../../Archive/7z/7zProperties.cpp \
../../Archive/7z/7zSpecStream.cpp \
../../Archive/7z/7zUpdate.cpp \
../../Common/InBuffer.cpp \
../../Common/InOutTempBuffer.cpp \
../../Common/LimitedStreams.cpp \
../../Common/LockedStream.cpp \
../../Common/LSBFDecoder.cpp \
../../Common/OutBuffer.cpp \
../../Common/ProgressUtils.cpp \
../../Common/StreamBinder.cpp \
../../Common/StreamObjects.cpp \
../../Common/StreamUtils.cpp

SRCS_C=../../Crypto/AES/aescrypt.c \
 ../../Crypto/AES/aeskey.c \
 ../../Crypto/AES/aestab.c

DllExports.o : ../../Archive/7z/DllExports.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/DllExports.cpp
Alloc.o : ../../../Common/Alloc.cpp
	$(CXX) $(CFLAGS) ../../../Common/Alloc.cpp
CRC.o : ../../../Common/CRC.cpp
	$(CXX) $(CFLAGS) ../../../Common/CRC.cpp
IntToString.o : ../../../Common/IntToString.cpp
	$(CXX) $(CFLAGS) ../../../Common/IntToString.cpp
String.o : ../../../Common/String.cpp
	$(CXX) $(CFLAGS) ../../../Common/String.cpp
StringConvert.o : ../../../Common/StringConvert.cpp
	$(CXX) $(CFLAGS) ../../../Common/StringConvert.cpp
StringToInt.o : ../../../Common/StringToInt.cpp
	$(CXX) $(CFLAGS) ../../../Common/StringToInt.cpp
Vector.o : ../../../Common/Vector.cpp
	$(CXX) $(CFLAGS) ../../../Common/Vector.cpp
Wildcard.o : ../../../Common/Wildcard.cpp
	$(CXX) $(CFLAGS) ../../../Common/Wildcard.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileIO.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
CoderMixer2.o : ../../Archive/Common/CoderMixer2.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2.cpp
CoderMixer2MT.o : ../../Archive/Common/CoderMixer2MT.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2MT.cpp
CrossThreadProgress.o : ../../Archive/Common/CrossThreadProgress.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CrossThreadProgress.cpp
FilterCoder.o : ../../Archive/Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/FilterCoder.cpp
InStreamWithCRC.o : ../../Archive/Common/InStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/InStreamWithCRC.cpp
ItemNameUtils.o : ../../Archive/Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ItemNameUtils.cpp
OutStreamWithCRC.o : ../../Archive/Common/OutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/OutStreamWithCRC.cpp
ParseProperties.o : ../../Archive/Common/ParseProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ParseProperties.cpp
MT.o : ../../Compress/LZ/MT/MT.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/MT/MT.cpp
LZInWindow.o : ../../Compress/LZ/LZInWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZInWindow.cpp
LZOutWindow.o : ../../Compress/LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZOutWindow.cpp
PPMDDecoder.o : ../../Compress/PPMD/PPMDDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDDecoder.cpp
PPMDEncoder.o : ../../Compress/PPMD/PPMDEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDEncoder.cpp
BranchCoder.o : ../../Compress/Branch/BranchCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BranchCoder.cpp
x86.o : ../../Compress/Branch/x86.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86.cpp
x86_2.o : ../../Compress/Branch/x86_2.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86_2.cpp
LZMADecoder.o : ../../Compress/LZMA/LZMADecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMADecoder.cpp
LZMAEncoder.o : ../../Compress/LZMA/LZMAEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMAEncoder.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
RangeCoderBit.o : ../../Compress/RangeCoder/RangeCoderBit.cpp
	$(CXX) $(CFLAGS) ../../Compress/RangeCoder/RangeCoderBit.cpp
DeflateDecoder.o : ../../Compress/Deflate/DeflateDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateDecoder.cpp
BZip2CRC.o : ../../Compress/BZip2/BZip2CRC.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2CRC.cpp
BZip2Decoder.o : ../../Compress/BZip2/BZip2Decoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2Decoder.cpp
MyAES.o : ../../Crypto/AES/MyAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/AES/MyAES.cpp
7zAES.o : ../../Crypto/7zAES/7zAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/7zAES.cpp
Sha256.o : ../../Crypto/Hash/Sha256.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/Sha256.cpp
7zCompressionMode.o : ../../Archive/7z/7zCompressionMode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zCompressionMode.cpp
7zDecode.o : ../../Archive/7z/7zDecode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zDecode.cpp
7zEncode.o : ../../Archive/7z/7zEncode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zEncode.cpp
7zExtract.o : ../../Archive/7z/7zExtract.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zExtract.cpp
7zFolderInStream.o : ../../Archive/7z/7zFolderInStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderInStream.cpp
7zFolderOutStream.o : ../../Archive/7z/7zFolderOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderOutStream.cpp
7zHandler.o : ../../Archive/7z/7zHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandler.cpp
7zHandlerOut.o : ../../Archive/7z/7zHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandlerOut.cpp
7zHeader.o : ../../Archive/7z/7zHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHeader.cpp
7zIn.o : ../../Archive/7z/7zIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zIn.cpp
7zMethodID.o : ../../Archive/7z/7zMethodID.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zMethodID.cpp
7zOut.o : ../../Archive/7z/7zOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zOut.cpp
7zProperties.o : ../../Archive/7z/7zProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zProperties.cpp
7zSpecStream.o : ../../Archive/7z/7zSpecStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zSpecStream.cpp
7zUpdate.o : ../../Archive/7z/7zUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zUpdate.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
InOutTempBuffer.o : ../../Common/InOutTempBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InOutTempBuffer.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
LockedStream.o : ../../Common/LockedStream.cpp
	$(CXX) $(CFLAGS) ../../Common/LockedStream.cpp
LSBFDecoder.o : ../../Common/LSBFDecoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFDecoder.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamBinder.o : ../../Common/StreamBinder.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamBinder.cpp
StreamObjects.o : ../../Common/StreamObjects.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamObjects.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
aescrypt.o : ../../Crypto/AES/aescrypt.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aescrypt.c
aeskey.o : ../../Crypto/AES/aeskey.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aeskey.c
aestab.o : ../../Crypto/AES/aestab.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aestab.c
