SRCS=\
 ../../Common/InBuffer.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/StreamUtils.cpp \
 ./DllExports.cpp \
 ../LZ/LZOutWindow.cpp \
 ./LZMADecoder.cpp \
 ./LZMAEncoder.cpp \
 ../RangeCoder/RangeCoderBit.cpp \
 ../../../Windows/Synchronization.cpp \
 ../../../../C/7zCrc.c \
 ../../../../C/Sort.c \
 ../../../../C/Threads.c \
 ../../../../C/Compress/Lz/MatchFinder.c \
 ../../../../C/Compress/Lz/MatchFinderMt.c

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
RangeCoderBit.o : ../RangeCoder/RangeCoderBit.cpp
	$(CXX) $(CFLAGS) ../RangeCoder/RangeCoderBit.cpp
LZOutWindow.o : ../LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../LZ/LZOutWindow.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
LZMADecoder.o : ./LZMADecoder.cpp
	$(CXX) $(CFLAGS) ./LZMADecoder.cpp
LZMAEncoder.o : ./LZMAEncoder.cpp
	$(CXX) $(CFLAGS) ./LZMAEncoder.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
7zCrc.o : ../../../../C/7zCrc.c
	$(CC) $(CFLAGS) ../../../../C/7zCrc.c
Sort.o : ../../../../C/Sort.c
	$(CC) $(CFLAGS) ../../../../C/Sort.c
Threads.o : ../../../../C/Threads.c
	$(CC) $(CFLAGS) ../../../../C/Threads.c
MatchFinder.o : ../../../../C/Compress/Lz/MatchFinder.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Lz/MatchFinder.c
MatchFinderMt.o : ../../../../C/Compress/Lz/MatchFinderMt.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Lz/MatchFinderMt.c
