PROG=../../../bin/Codecs/Copy.so

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

OBJS=\
../../../Common/MyWindows.o\
DllExports.o\
../../../Common/Alloc.o\
StreamUtils.o\
CopyCoder.o

include ../../../makefile.glb

