#
# makefile for AIX
# tested with AIX 5.3 and g++ 4.1.0
#

OPTFLAGS=-O

ALLFLAGS=${OPTFLAGS} -s -fPIC \
        -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
        -DNDEBUG -D_REENTRANT -DENV_UNIX \
        $(LOCAL_FLAGS)

CXX=g++ $(ALLFLAGS)
CC=gcc $(ALLFLAGS)
LINK_SHARED=-shared

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

