PROG=../../../bin/Formats/rpm.so

LOCAL_FLAGS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

MY_WINDOWS=

OBJS = \
../../../Common/MyWindows.o \
DllExports.o\
StreamUtils.o \
PropVariant.o\
ProgressUtils.o\
CopyCoder.o\
../../../Common/Alloc.o\
RpmHandler.o\
RpmIn.o

include ../../../makefile.glb

