SRCS=\
 ../Common/CodecsPath.cpp \
 ../Common/DummyOutStream.cpp \
 ../../Common/InBuffer.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Compress/Z/ZDecoder.cpp \
 ./DllExports.cpp \
 ../../../Windows/PropVariant.cpp \
 ./ZHandler.cpp

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
ZHandler.o : ./ZHandler.cpp
	$(CXX) $(CFLAGS) ./ZHandler.cpp
ZDecoder.o : ../../Compress/Z/ZDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Z/ZDecoder.cpp
CodecsPath.o : ../Common/CodecsPath.cpp
	$(CXX) $(CFLAGS) ../Common/CodecsPath.cpp
DummyOutStream.o : ../Common/DummyOutStream.cpp
	$(CXX) $(CFLAGS) ../Common/DummyOutStream.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
