PROG=../../../bin/Formats/split.so

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

OBJS = \
../../../Common/Alloc.o \
../../../Common/MyWindows.o \
../../../Common/Vector.o \
../../../Common/StringConvert.o \
../../../Common/String.o \
DllExports.o \
PropVariant.o \
CopyCoder.o \
ProgressUtils.o \
StreamUtils.o \
SplitHandler.o \
SplitHandlerOut.o \
MultiStream.o 

include ../../../makefile.glb

