SRCS=\
 ../Common/MultiStream.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Compress/Copy/CopyCoder.cpp \
 ./DllExports.cpp \
 ./SplitHandler.cpp \
 ./SplitHandlerOut.cpp \
 ../../../Windows/PropVariant.cpp

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
SplitHandler.o : ./SplitHandler.cpp
	$(CXX) $(CFLAGS) ./SplitHandler.cpp
SplitHandlerOut.o : ./SplitHandlerOut.cpp
	$(CXX) $(CFLAGS) ./SplitHandlerOut.cpp
MultiStream.o : ../Common/MultiStream.cpp
	$(CXX) $(CFLAGS) ../Common/MultiStream.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
