SRCS=\
 ../../Archive/7z/7zCompressionMode.cpp \
 ../../Archive/7z/7zDecode.cpp \
 ../../Archive/7z/7zEncode.cpp \
 ../../Archive/7z/7zExtract.cpp \
 ../../Archive/7z/7zFolderInStream.cpp \
 ../../Archive/7z/7zFolderOutStream.cpp \
 ../../Archive/7z/7zHandler.cpp \
 ../../Archive/7z/7zHandlerOut.cpp \
 ../../Archive/7z/7zHeader.cpp \
 ../../Archive/7z/7zIn.cpp \
 ../../Archive/7z/7zMethodID.cpp \
 ../../Archive/7z/7zOut.cpp \
 ../../Archive/7z/7zProperties.cpp \
 ../../Archive/7z/7zSpecStream.cpp \
 ../../Archive/7z/7zUpdate.cpp \
 ../../Archive/BZip2/BZip2Handler.cpp \
 ../../Archive/BZip2/BZip2HandlerOut.cpp \
 ../../Archive/BZip2/BZip2Update.cpp \
 ../../Archive/Common/CoderMixer2.cpp \
 ../../Archive/Common/CoderMixer2MT.cpp \
 ../../Archive/Common/CrossThreadProgress.cpp \
 ../../Archive/Common/DummyOutStream.cpp \
 ../../Archive/Common/FilterCoder.cpp \
 ../../Archive/Common/InStreamWithCRC.cpp \
 ../../Archive/Common/ItemNameUtils.cpp \
 ../../Archive/Common/MultiStream.cpp \
 ../../Archive/Common/OutStreamWithCRC.cpp \
 ../../Archive/GZip/GZipHandler.cpp \
 ../../Archive/GZip/GZipHandlerOut.cpp \
 ../../Archive/GZip/GZipHeader.cpp \
 ../../Archive/GZip/GZipIn.cpp \
 ../../Archive/GZip/GZipOut.cpp \
 ../../Archive/GZip/GZipUpdate.cpp \
 ../../Archive/Split/SplitHandler.cpp \
 ../../Archive/Tar/TarHandler.cpp \
 ../../Archive/Tar/TarHandlerOut.cpp \
 ../../Archive/Tar/TarHeader.cpp \
 ../../Archive/Tar/TarIn.cpp \
 ../../Archive/Tar/TarOut.cpp \
 ../../Archive/Tar/TarUpdate.cpp \
 ../../Archive/Zip/ZipAddCommon.cpp \
 ../../Archive/Zip/ZipHandler.cpp \
 ../../Archive/Zip/ZipHandlerOut.cpp \
 ../../Archive/Zip/ZipHeader.cpp \
 ../../Archive/Zip/ZipIn.cpp \
 ../../Archive/Zip/ZipItem.cpp \
 ../../Archive/Zip/ZipOut.cpp \
 ../../Archive/Zip/ZipUpdate.cpp \
 ../../Archive/Z/ZHandler.cpp \
 ../../Common/FilePathAutoRename.cpp \
 ../../Common/FileStreams.cpp \
 ../../Common/InBuffer.cpp \
 ../../Common/InOutTempBuffer.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/LockedStream.cpp \
 ../../Common/LSBFDecoder.cpp \
 ../../Common/LSBFEncoder.cpp \
 ../../Common/OffsetStream.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamBinder.cpp \
 ../../Common/StreamObjects.cpp \
 ../../Compress/Branch/BranchCoder.cpp \
 ../../Compress/Branch/x86_2.cpp \
 ../../Compress/Branch/x86.cpp \
 ../../Compress/BWT/BlockSort.cpp \
 ../../Compress/BZip2/BZip2CRC.cpp \
 ../../Compress/BZip2/BZip2Decoder.cpp \
 ../../Compress/BZip2/BZip2Encoder.cpp \
 ../../Compress/Copy/CopyCoder.cpp \
 ../../Compress/Deflate/DeflateDecoder.cpp \
 ../../Compress/Deflate/DeflateEncoder.cpp \
 ../../Compress/Huffman/HuffmanEncoder.cpp \
 ../../Compress/Implode/ImplodeDecoder.cpp \
 ../../Compress/Implode/ImplodeHuffmanDecoder.cpp \
 ../../Compress/LZ/LZInWindow.cpp \
 ../../Compress/LZ/LZOutWindow.cpp \
 ../../Compress/LZMA/LZMADecoder.cpp \
 ../../Compress/LZMA/LZMAEncoder.cpp \
 ../../Compress/LZ/MT/MT.cpp \
 ../../Compress/PPMD/PPMDDecoder.cpp \
 ../../Compress/PPMD/PPMDEncoder.cpp \
 ../../Compress/RangeCoder/RangeCoderBit.cpp \
 ../../Compress/Shrink/ShrinkDecoder.cpp \
 ../../Compress/Z/ZDecoder.cpp \
 ../../Crypto/7zAES/7zAES.cpp \
 ../../Crypto/7zAES/SHA256.cpp \
 ../../Crypto/AES/MyAES.cpp \
 ../../Crypto/Zip/ZipCipher.cpp \
 ../../Crypto/Zip/ZipCrypto.cpp \
 ../../UI/Common/ArchiveCommandLine.cpp \
 ../../UI/Common/ArchiveExtractCallback.cpp \
 ../../UI/Common/ArchiveOpenCallback.cpp \
 ../../UI/Common/ArchiverInfo.cpp \
 ../../UI/Common/DefaultName.cpp \
 ../../UI/Common/EnumDirItems.cpp \
 ../../UI/Common/Extract.cpp \
 ../../UI/Common/ExtractingFilePath.cpp \
 ../../UI/Common/OpenArchive.cpp \
 ../../UI/Common/PropIDUtils.cpp \
 ../../UI/Common/SortUtils.cpp \
 ../../UI/Common/TempFiles.cpp \
 ../../UI/Common/UpdateAction.cpp \
 ../../UI/Common/UpdateCallback.cpp \
 ../../UI/Common/Update.cpp \
 ../../UI/Common/UpdatePair.cpp \
 ../../UI/Common/UpdateProduce.cpp \
 ../../UI/Console/ConsoleClose.cpp \
 ../../UI/Console/ExtractCallbackConsole.cpp \
 ../../UI/Console/List.cpp \
 ../../UI/Console/MainAr.cpp \
 ../../UI/Console/Main.cpp \
 ../../UI/Console/OpenCallbackConsole.cpp \
 ../../UI/Console/PercentPrinter.cpp \
 ../../UI/Console/UpdateCallbackConsole.cpp \
 ../../UI/Console/UserInputUtils.cpp \
 ../../../Windows/Error.cpp \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/FileName.cpp \
 ../../../Windows/PropVariantConversions.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/Synchronization.cpp

 SRCS_C=../../Crypto/AES/aescrypt.c \
 ../../Crypto/AES/aeskey.c \
 ../../Crypto/AES/aestab.c 

ConsoleClose.o : ../../UI/Console/ConsoleClose.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/ConsoleClose.cpp
ExtractCallbackConsole.o : ../../UI/Console/ExtractCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/ExtractCallbackConsole.cpp
List.o : ../../UI/Console/List.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/List.cpp
Main.o : ../../UI/Console/Main.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/Main.cpp
MainAr.o : ../../UI/Console/MainAr.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/MainAr.cpp
OpenCallbackConsole.o : ../../UI/Console/OpenCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/OpenCallbackConsole.cpp
PercentPrinter.o : ../../UI/Console/PercentPrinter.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/PercentPrinter.cpp
UpdateCallbackConsole.o : ../../UI/Console/UpdateCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/UpdateCallbackConsole.cpp
UserInputUtils.o : ../../UI/Console/UserInputUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/UserInputUtils.cpp
Error.o : ../../../Windows/Error.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Error.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariantConversions.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
CrossThreadProgress.o : ../../Archive/Common/CrossThreadProgress.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CrossThreadProgress.cpp
FilePathAutoRename.o : ../../Common/FilePathAutoRename.cpp
	$(CXX) $(CFLAGS) ../../Common/FilePathAutoRename.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/FileStreams.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
InOutTempBuffer.o : ../../Common/InOutTempBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InOutTempBuffer.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
LockedStream.o : ../../Common/LockedStream.cpp
	$(CXX) $(CFLAGS) ../../Common/LockedStream.cpp
LSBFDecoder.o : ../../Common/LSBFDecoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFDecoder.cpp
LSBFEncoder.o : ../../Common/LSBFEncoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFEncoder.cpp
OffsetStream.o : ../../Common/OffsetStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OffsetStream.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamBinder.o : ../../Common/StreamBinder.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamBinder.cpp
StreamObjects.o : ../../Common/StreamObjects.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamObjects.cpp
BranchCoder.o : ../../Compress/Branch/BranchCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BranchCoder.cpp
x86.o : ../../Compress/Branch/x86.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86.cpp
x86_2.o : ../../Compress/Branch/x86_2.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86_2.cpp
BZip2Decoder.o : ../../Compress/BZip2/BZip2Decoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2Decoder.cpp
BZip2Encoder.o : ../../Compress/BZip2/BZip2Encoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2Encoder.cpp
BZip2CRC.o : ../../Compress/BZip2/BZip2CRC.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2CRC.cpp
BlockSort.o : ../../Compress/BWT/BlockSort.cpp
	$(CXX) $(CFLAGS) ../../Compress/BWT/BlockSort.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
DeflateDecoder.o : ../../Compress/Deflate/DeflateDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateDecoder.cpp
DeflateEncoder.o : ../../Compress/Deflate/DeflateEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateEncoder.cpp
HuffmanEncoder.o : ../../Compress/Huffman/HuffmanEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Huffman/HuffmanEncoder.cpp
ImplodeDecoder.o : ../../Compress/Implode/ImplodeDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Implode/ImplodeDecoder.cpp
ImplodeHuffmanDecoder.o : ../../Compress/Implode/ImplodeHuffmanDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Implode/ImplodeHuffmanDecoder.cpp
MT.o : ../../Compress/LZ/MT/MT.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/MT/MT.cpp
LZInWindow.o : ../../Compress/LZ/LZInWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZInWindow.cpp
LZOutWindow.o : ../../Compress/LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZOutWindow.cpp
LZMADecoder.o : ../../Compress/LZMA/LZMADecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMADecoder.cpp
LZMAEncoder.o : ../../Compress/LZMA/LZMAEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMAEncoder.cpp
PPMDDecoder.o : ../../Compress/PPMD/PPMDDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDDecoder.cpp
PPMDEncoder.o : ../../Compress/PPMD/PPMDEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDEncoder.cpp
RangeCoderBit.o : ../../Compress/RangeCoder/RangeCoderBit.cpp
	$(CXX) $(CFLAGS) ../../Compress/RangeCoder/RangeCoderBit.cpp
7zCompressionMode.o : ../../Archive/7z/7zCompressionMode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zCompressionMode.cpp
7zDecode.o : ../../Archive/7z/7zDecode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zDecode.cpp
7zEncode.o : ../../Archive/7z/7zEncode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zEncode.cpp
7zExtract.o : ../../Archive/7z/7zExtract.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zExtract.cpp
7zFolderInStream.o : ../../Archive/7z/7zFolderInStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderInStream.cpp
7zFolderOutStream.o : ../../Archive/7z/7zFolderOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderOutStream.cpp
7zHandler.o : ../../Archive/7z/7zHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandler.cpp
7zHandlerOut.o : ../../Archive/7z/7zHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandlerOut.cpp
7zHeader.o : ../../Archive/7z/7zHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHeader.cpp
7zIn.o : ../../Archive/7z/7zIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zIn.cpp
7zMethodID.o : ../../Archive/7z/7zMethodID.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zMethodID.cpp
7zOut.o : ../../Archive/7z/7zOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zOut.cpp
7zProperties.o : ../../Archive/7z/7zProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zProperties.cpp
7zSpecStream.o : ../../Archive/7z/7zSpecStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zSpecStream.cpp
7zUpdate.o : ../../Archive/7z/7zUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zUpdate.cpp
BZip2Handler.o : ../../Archive/BZip2/BZip2Handler.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/BZip2Handler.cpp
BZip2HandlerOut.o : ../../Archive/BZip2/BZip2HandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/BZip2HandlerOut.cpp
BZip2Update.o : ../../Archive/BZip2/BZip2Update.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/BZip2Update.cpp
GZipHandler.o : ../../Archive/GZip/GZipHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipHandler.cpp
GZipHandlerOut.o : ../../Archive/GZip/GZipHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipHandlerOut.cpp
GZipHeader.o : ../../Archive/GZip/GZipHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipHeader.cpp
GZipIn.o : ../../Archive/GZip/GZipIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipIn.cpp
GZipOut.o : ../../Archive/GZip/GZipOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipOut.cpp
GZipUpdate.o : ../../Archive/GZip/GZipUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipUpdate.cpp
TarHandler.o : ../../Archive/Tar/TarHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarHandler.cpp
TarHandlerOut.o : ../../Archive/Tar/TarHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarHandlerOut.cpp
TarHeader.o : ../../Archive/Tar/TarHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarHeader.cpp
TarIn.o : ../../Archive/Tar/TarIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarIn.cpp
TarOut.o : ../../Archive/Tar/TarOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarOut.cpp
TarUpdate.o : ../../Archive/Tar/TarUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarUpdate.cpp
ZipAddCommon.o : ../../Archive/Zip/ZipAddCommon.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipAddCommon.cpp
ZipHandler.o : ../../Archive/Zip/ZipHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipHandler.cpp
ZipHandlerOut.o : ../../Archive/Zip/ZipHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipHandlerOut.cpp
ZipHeader.o : ../../Archive/Zip/ZipHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipHeader.cpp
ZipIn.o : ../../Archive/Zip/ZipIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipIn.cpp
ZipItem.o : ../../Archive/Zip/ZipItem.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipItem.cpp
ZipOut.o : ../../Archive/Zip/ZipOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipOut.cpp
ZipUpdate.o : ../../Archive/Zip/ZipUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipUpdate.cpp
CoderMixer2.o : ../../Archive/Common/CoderMixer2.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2.cpp
CoderMixer2MT.o : ../../Archive/Common/CoderMixer2MT.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2MT.cpp
DummyOutStream.o : ../../Archive/Common/DummyOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/DummyOutStream.cpp
FilterCoder.o : ../../Archive/Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/FilterCoder.cpp
InStreamWithCRC.o : ../../Archive/Common/InStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/InStreamWithCRC.cpp
ItemNameUtils.o : ../../Archive/Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ItemNameUtils.cpp
OutStreamWithCRC.o : ../../Archive/Common/OutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/OutStreamWithCRC.cpp
MultiStream.o : ../../Archive/Common/MultiStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/MultiStream.cpp
ArchiveCommandLine.o : ../../UI/Common/ArchiveCommandLine.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveCommandLine.cpp
ArchiveExtractCallback.o : ../../UI/Common/ArchiveExtractCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveExtractCallback.cpp
ArchiveOpenCallback.o : ../../UI/Common/ArchiveOpenCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveOpenCallback.cpp
ArchiverInfo.o : ../../UI/Common/ArchiverInfo.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiverInfo.cpp
DefaultName.o : ../../UI/Common/DefaultName.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/DefaultName.cpp
EnumDirItems.o : ../../UI/Common/EnumDirItems.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/EnumDirItems.cpp
Extract.o : ../../UI/Common/Extract.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/Extract.cpp
ExtractingFilePath.o : ../../UI/Common/ExtractingFilePath.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ExtractingFilePath.cpp
OpenArchive.o : ../../UI/Common/OpenArchive.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/OpenArchive.cpp
PropIDUtils.o : ../../UI/Common/PropIDUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/PropIDUtils.cpp
SortUtils.o : ../../UI/Common/SortUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/SortUtils.cpp
TempFiles.o : ../../UI/Common/TempFiles.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/TempFiles.cpp
Update.o : ../../UI/Common/Update.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/Update.cpp
UpdateAction.o : ../../UI/Common/UpdateAction.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdateAction.cpp
UpdateCallback.o : ../../UI/Common/UpdateCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdateCallback.cpp
UpdatePair.o : ../../UI/Common/UpdatePair.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdatePair.cpp
UpdateProduce.o : ../../UI/Common/UpdateProduce.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/UpdateProduce.cpp
ZipCipher.o : ../../Crypto/Zip/ZipCipher.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Zip/ZipCipher.cpp
ZipCrypto.o : ../../Crypto/Zip/ZipCrypto.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Zip/ZipCrypto.cpp
MyAES.o : ../../Crypto/AES/MyAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/AES/MyAES.cpp
7zAES.o : ../../Crypto/7zAES/7zAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/7zAES.cpp
SHA256.o : ../../Crypto/7zAES/SHA256.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/SHA256.cpp
SplitHandler.o : ../../Archive/Split/SplitHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Split/SplitHandler.cpp
aescrypt.o : ../../Crypto/AES/aescrypt.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aescrypt.c
aeskey.o : ../../Crypto/AES/aeskey.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aeskey.c
aestab.o : ../../Crypto/AES/aestab.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aestab.c
ShrinkDecoder.o : ../../Compress/Shrink/ShrinkDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Shrink/ShrinkDecoder.cpp
ZHandler.o : ../../Archive/Z/ZHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Z/ZHandler.cpp
ZDecoder.o : ../../Compress/Z/ZDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Z/ZDecoder.cpp
