PROG=../../../bin/Formats/Tar.so

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

OBJS = \
../../../Common/MyWindows.o \
../../../Common/Alloc.o\
../../../Common/Vector.o\
../../../Common/StringConvert.o\
../../../Common/String.o\
../../../Common/IntToString.o\
../../../Common/StringToInt.o\
DllExports.o\
PropVariant.o\
CopyCoder.o\
TarHandler.o\
TarHandlerOut.o\
TarHeader.o\
TarIn.o\
TarOut.o\
TarUpdate.o\
ItemNameUtils.o\
LimitedStreams.o\
StreamUtils.o \
ProgressUtils.o

include ../../../makefile.glb

