SRCS=\
 ../7z/7zMethodID.cpp \
 ../7z/7zMethods.cpp \
 ../Common/CodecsPath.cpp \
 ../Common/CoderLoader.cpp \
 ../Common/CrossThreadProgress.cpp \
 ../Common/FilterCoder.cpp \
 ../../Common/InBuffer.cpp \
 ../Common/InStreamWithCRC.cpp \
 ../Common/ItemNameUtils.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/LSBFDecoder.cpp \
 ../../Common/OffsetStream.cpp \
 ../../Common/OutBuffer.cpp \
 ../Common/OutStreamWithCRC.cpp \
 ../Common/ParseProperties.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamBinder.cpp \
 ../../Common/StreamObjects.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/MemBlocks.cpp \
 ../../Common/OutMemStream.cpp \
 ../../Common/ProgressMt.cpp \
 ../../Common/OffsetStream.cpp \
 ../../Compress/Copy/CopyCoder.cpp \
 ../../Compress/Implode/ImplodeDecoder.cpp \
 ../../Compress/Implode/ImplodeHuffmanDecoder.cpp \
 ../../Compress/LZ/LZOutWindow.cpp \
 ../../Compress/Shrink/ShrinkDecoder.cpp \
 ../../Crypto/Zip/ZipCipher.cpp \
 ../../Crypto/Zip/ZipCrypto.cpp \
 ../../Crypto/Hash/Pbkdf2HmacSha1.cpp \
 ../../Crypto/Hash/HmacSha1.cpp \
 ../../Crypto/Hash/Sha1.cpp \
 ../../Crypto/Hash/RandGen.cpp \
 ../../Crypto/WzAES/WzAES.cpp \
 ./DllExports.cpp \
 ../../../Windows/DLL.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/Synchronization.cpp \
 ./ZipAddCommon.cpp \
 ./ZipHandler.cpp \
 ./ZipHandlerOut.cpp \
 ./ZipHeader.cpp \
 ./ZipIn.cpp \
 ./ZipItem.cpp \
 ./ZipOut.cpp \
 ./ZipUpdate.cpp

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
DLL.o : ../../../Windows/DLL.cpp
	$(CXX) $(CFLAGS) ../../../Windows/DLL.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
CodecsPath.o : ../Common/CodecsPath.cpp
	$(CXX) $(CFLAGS) ../Common/CodecsPath.cpp
CoderLoader.o : ../Common/CoderLoader.cpp
	$(CXX) $(CFLAGS) ../Common/CoderLoader.cpp
CrossThreadProgress.o : ../Common/CrossThreadProgress.cpp
	$(CXX) $(CFLAGS) ../Common/CrossThreadProgress.cpp
FilterCoder.o : ../Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../Common/FilterCoder.cpp
InStreamWithCRC.o : ../Common/InStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../Common/InStreamWithCRC.cpp
ItemNameUtils.o : ../Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../Common/ItemNameUtils.cpp
OutStreamWithCRC.o : ../Common/OutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../Common/OutStreamWithCRC.cpp
ParseProperties.o : ../Common/ParseProperties.cpp
	$(CXX) $(CFLAGS) ../Common/ParseProperties.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
OffsetStream.o : ../../Common/OffsetStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OffsetStream.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamBinder.o : ../../Common/StreamBinder.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamBinder.cpp
StreamObjects.o : ../../Common/StreamObjects.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamObjects.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
MemBlocks.o : ../../Common/MemBlocks.cpp
	$(CXX) $(CFLAGS) ../../Common/MemBlocks.cpp
OutMemStream.o : ../../Common/OutMemStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OutMemStream.cpp
ProgressMt.o : ../../Common/ProgressMt.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressMt.cpp
ZipAddCommon.o : ./ZipAddCommon.cpp
	$(CXX) $(CFLAGS) ./ZipAddCommon.cpp
ZipHandler.o : ./ZipHandler.cpp
	$(CXX) $(CFLAGS) ./ZipHandler.cpp
ZipHandlerOut.o : ./ZipHandlerOut.cpp
	$(CXX) $(CFLAGS) ./ZipHandlerOut.cpp
ZipHeader.o : ./ZipHeader.cpp
	$(CXX) $(CFLAGS) ./ZipHeader.cpp
ZipIn.o : ./ZipIn.cpp
	$(CXX) $(CFLAGS) ./ZipIn.cpp
ZipItem.o : ./ZipItem.cpp
	$(CXX) $(CFLAGS) ./ZipItem.cpp
ZipOut.o : ./ZipOut.cpp
	$(CXX) $(CFLAGS) ./ZipOut.cpp
ZipUpdate.o : ./ZipUpdate.cpp
	$(CXX) $(CFLAGS) ./ZipUpdate.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
ShrinkDecoder.o : ../../Compress/Shrink/ShrinkDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Shrink/ShrinkDecoder.cpp
ZipCipher.o : ../../Crypto/Zip/ZipCipher.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Zip/ZipCipher.cpp
ZipCrypto.o : ../../Crypto/Zip/ZipCrypto.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Zip/ZipCrypto.cpp
Pbkdf2HmacSha1.o : ../../Crypto/Hash/Pbkdf2HmacSha1.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/Pbkdf2HmacSha1.cpp
HmacSha1.o : ../../Crypto/Hash/HmacSha1.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/HmacSha1.cpp
Sha1.o : ../../Crypto/Hash/Sha1.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/Sha1.cpp
RandGen.o : ../../Crypto/Hash/RandGen.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/RandGen.cpp
WzAES.o : ../../Crypto/WzAES/WzAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/WzAES/WzAES.cpp
7zMethodID.o : ../7z/7zMethodID.cpp
	$(CXX) $(CFLAGS) ../7z/7zMethodID.cpp
7zMethods.o : ../7z/7zMethods.cpp
	$(CXX) $(CFLAGS) ../7z/7zMethods.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
ImplodeDecoder.o : ../../Compress/Implode/ImplodeDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Implode/ImplodeDecoder.cpp
ImplodeHuffmanDecoder.o : ../../Compress/Implode/ImplodeHuffmanDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Implode/ImplodeHuffmanDecoder.cpp
LZOutWindow.o : ../../Compress/LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZOutWindow.cpp
LSBFDecoder.o : ../../Common/LSBFDecoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFDecoder.cpp
