PROG=../../../../bin/7za.so

LOCAL_FLAGS=\
  -DCOMPRESS_MT \
  -DCOMPRESS_MF_MT \
  -DCOMPRESS_BZIP2_MT \
  -DDEFLATE_EXTRACT_ONLY \
  -DBZIP2_EXTRACT_ONLY

include ../../../../makefile.crc32
include ../../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS_DLL)

MY_WINDOWS= \

OBJS = \
myGetTickCount.o \
wine_date_and_time.o \
CRC.o \
IntToString.o \
MyString.o \
StringConvert.o \
StringToInt.o \
MyVector.o \
MyWindows.o \
Wildcard.o \
FileDir.o \
FileFind.o \
FileIO.o \
PropVariant.o \
Synchronization.o \
System.o \
CreateCoder.o \
InBuffer.o \
InOutTempBuffer.o \
FilterCoder.o \
LimitedStreams.o \
LockedStream.o \
LSBFDecoder.o \
MethodId.o \
MethodProps.o \
VirtThread.o \
OutBuffer.o \
ProgressUtils.o \
StreamBinder.o \
StreamObjects.o \
StreamUtils.o \
ArchiveExports.o \
DllExports2.o \
CoderMixer2.o \
CoderMixer2MT.o \
CrossThreadProgress.o \
InStreamWithCRC.o \
HandlerOut.o \
ItemNameUtils.o \
OutStreamWithCRC.o \
ParseProperties.o \
7zCompressionMode.o \
7zDecode.o \
7zEncode.o \
7zExtract.o \
7zFolderInStream.o \
7zFolderOutStream.o \
7zHandler.o \
7zHandlerOut.o \
7zHeader.o \
7zIn.o \
7zOut.o \
7zProperties.o \
7zSpecStream.o \
7zUpdate.o \
7zRegister.o \
CodecExports.o \
BranchCoder.o \
x86.o \
x86_2.o \
ARM.o \
ARMThumb.o \
IA64.o \
PPC.o \
SPARC.o \
BranchRegister.o \
BCJRegister.o \
BCJ2Register.o \
ByteSwap.o \
ByteSwapRegister.o \
BZip2CRC.o \
BZip2Register.o \
BZip2Decoder.o \
CopyCoder.o \
CopyRegister.o \
DeflateDecoder.o \
DeflateRegister.o \
LZOutWindow.o \
LZMADecoder.o \
LZMAEncoder.o \
LZMARegister.o \
PPMDDecoder.o \
PPMDEncoder.o \
PPMDRegister.o \
7zAES.o \
7zAESRegister.o \
MyAES.o \
RandGen.o \
Sha1.o \
Sha256.o \
Threads.o \
$(OBJ_CRC32) \
MatchFinder.o \
MatchFinderMt.o \
BranchARM.o \
BranchARMThumb.o \
BranchIA64.o \
BranchPPC.o \
BranchSPARC.o \
BranchX86.o \
RangeCoderBit.o \
Aes.o

include ../../../../makefile.glb

