SRCS=\
../../../Common/CRC.cpp \
../../../Common/IntToString.cpp \
../../../Common/String.cpp \
../../../Common/StringConvert.cpp \
../../../Common/StringToInt.cpp \
../../../Common/Vector.cpp \
../../../Common/Wildcard.cpp \
../../../Windows/FileDir.cpp \
../../../Windows/FileFind.cpp \
../../../Windows/FileIO.cpp \
../../../Windows/PropVariant.cpp \
../../../Windows/Synchronization.cpp \
../../Archive/Common/CoderMixer2.cpp \
../../Archive/Common/CoderMixer2MT.cpp \
../../Archive/Common/CrossThreadProgress.cpp \
../../Archive/Common/InStreamWithCRC.cpp \
../../Archive/Common/ItemNameUtils.cpp \
../../Archive/Common/OutStreamWithCRC.cpp \
../../Archive/Common/ParseProperties.cpp \
../../Compress/LZ/LZOutWindow.cpp \
../../Compress/PPMD/PPMDDecoder.cpp \
../../Compress/PPMD/PPMDEncoder.cpp \
../../Compress/Branch/BranchCoder.cpp \
../../Compress/Branch/x86.cpp \
../../Compress/Branch/x86_2.cpp \
../../Compress/LZMA/LZMADecoder.cpp \
../../Compress/LZMA/LZMAEncoder.cpp \
../../Compress/Copy/CopyCoder.cpp \
../../Compress/RangeCoder/RangeCoderBit.cpp \
../../Compress/Deflate/DeflateDecoder.cpp \
../../Compress/BZip2/BZip2CRC.cpp \
../../Compress/BZip2/BZip2Decoder.cpp \
../../Crypto/AES/MyAES.cpp \
../../Crypto/7zAES/7zAES.cpp \
../../Crypto/Hash/Sha256.cpp \
../../Archive/7z/7zDecode.cpp \
../../Archive/7z/7zEncode.cpp \
../../Archive/7z/7zExtract.cpp \
../../Archive/7z/7zFolderInStream.cpp \
../../Archive/7z/7zFolderOutStream.cpp \
../../Archive/7z/7zHandler.cpp \
../../Archive/7z/7zHandlerOut.cpp \
../../Archive/7z/7zHeader.cpp \
../../Archive/7z/7zIn.cpp \
../../Archive/7z/7zOut.cpp \
../../Archive/7z/7zProperties.cpp \
../../Archive/7z/7zSpecStream.cpp \
../../Archive/7z/7zUpdate.cpp \
../../Common/InBuffer.cpp \
../../Common/InOutTempBuffer.cpp \
../../Common/LimitedStreams.cpp \
../../Common/LockedStream.cpp \
../../Common/LSBFDecoder.cpp \
../../Common/OutBuffer.cpp \
../../Common/ProgressUtils.cpp \
../../Common/StreamBinder.cpp \
../../Common/StreamObjects.cpp \
../../Common/StreamUtils.cpp \

SRCS_C=../../Crypto/AES/aescrypt.c \
 ../../Crypto/AES/aeskey.c \
 ../../Crypto/AES/aestab.c \
../../../../C/Compress/Lz/MatchFinder.c \
../../../../C/Compress/Lz/MatchFinderMt.c \
../../../../C/7zCrc.c \
../../../../C/Threads.c

ArchiveExports.o : ../../Archive/ArchiveExports.cpp
	$(CXX) $(CFLAGS) ../../Archive/ArchiveExports.cpp
CodecExports.o : ../../Compress/CodecExports.cpp
	$(CXX) $(CFLAGS) ../../Compress/CodecExports.cpp
DllExports2.o : ../../Archive/DllExports2.cpp
	$(CXX) $(CFLAGS) ../../Archive/DllExports2.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileIO.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
LZOutWindow.o : ../../Compress/LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZOutWindow.cpp
PPMDDecoder.o : ../../Compress/PPMD/PPMDDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDDecoder.cpp
PPMDEncoder.o : ../../Compress/PPMD/PPMDEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDEncoder.cpp
PPMDRegister.o : ../../Compress/PPMD/PPMDRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDRegister.cpp
ARM.o : ../../Compress/Branch/ARM.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/ARM.cpp
ARMThumb.o : ../../Compress/Branch/ARMThumb.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/ARMThumb.cpp
BCJ2Register.o : ../../Compress/Branch/BCJ2Register.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BCJ2Register.cpp
BCJRegister.o : ../../Compress/Branch/BCJRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BCJRegister.cpp
BranchCoder.o : ../../Compress/Branch/BranchCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BranchCoder.cpp
BranchRegister.o : ../../Compress/Branch/BranchRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BranchRegister.cpp
IA64.o : ../../Compress/Branch/IA64.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/IA64.cpp
PPC.o : ../../Compress/Branch/PPC.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/PPC.cpp
SPARC.o : ../../Compress/Branch/SPARC.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/SPARC.cpp
x86.o : ../../Compress/Branch/x86.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86.cpp
x86_2.o : ../../Compress/Branch/x86_2.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86_2.cpp
LZMADecoder.o : ../../Compress/LZMA/LZMADecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMADecoder.cpp
LZMAEncoder.o : ../../Compress/LZMA/LZMAEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMAEncoder.cpp
LZMARegister.o : ../../Compress/LZMA/LZMARegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMARegister.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
CopyRegister.o : ../../Compress/Copy/CopyRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyRegister.cpp
RangeCoderBit.o : ../../Compress/RangeCoder/RangeCoderBit.cpp
	$(CXX) $(CFLAGS) ../../Compress/RangeCoder/RangeCoderBit.cpp
Deflate64Register.o : ../../Compress/Deflate/Deflate64Register.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/Deflate64Register.cpp
DeflateDecoder.o : ../../Compress/Deflate/DeflateDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateDecoder.cpp
DeflateEncoder.o : ../../Compress/Deflate/DeflateEncoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateEncoder.cpp
DeflateNsisRegister.o : ../../Compress/Deflate/DeflateNsisRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateNsisRegister.cpp
DeflateRegister.o : ../../Compress/Deflate/DeflateRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/Deflate/DeflateRegister.cpp
BZip2CRC.o : ../../Compress/BZip2/BZip2CRC.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2CRC.cpp
BZip2Decoder.o : ../../Compress/BZip2/BZip2Decoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2Decoder.cpp
BZip2Encoder.o : ../../Compress/BZip2/BZip2Encoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2Encoder.cpp
BZip2Register.o : ../../Compress/BZip2/BZip2Register.cpp
	$(CXX) $(CFLAGS) ../../Compress/BZip2/BZip2Register.cpp
Rar1Decoder.o : ../../Compress/Rar/Rar1Decoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Rar/Rar1Decoder.cpp
Rar2Decoder.o : ../../Compress/Rar/Rar2Decoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Rar/Rar2Decoder.cpp
Rar3Decoder.o : ../../Compress/Rar/Rar3Decoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Rar/Rar3Decoder.cpp
Rar3Vm.o : ../../Compress/Rar/Rar3Vm.cpp
	$(CXX) $(CFLAGS) ../../Compress/Rar/Rar3Vm.cpp
RarCodecsRegister.o : ../../Compress/Rar/RarCodecsRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/Rar/RarCodecsRegister.cpp
BlockSort.o : ../../Compress/BWT/BlockSort.cpp
	$(CXX) $(CFLAGS) ../../Compress/BWT/BlockSort.cpp
ImplodeDecoder.o : ../../Compress/Implode/ImplodeDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Implode/ImplodeDecoder.cpp
ImplodeHuffmanDecoder.o : ../../Compress/Implode/ImplodeHuffmanDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Implode/ImplodeHuffmanDecoder.cpp
Lzx86Converter.o : ../../Compress/Lzx/Lzx86Converter.cpp
	$(CXX) $(CFLAGS) ../../Compress/Lzx/Lzx86Converter.cpp
LzxDecoder.o : ../../Compress/Lzx/LzxDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Lzx/LzxDecoder.cpp
ZDecoder.o : ../../Compress/Z/ZDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Z/ZDecoder.cpp
ArjDecoder1.o : ../../Compress/Arj/ArjDecoder1.cpp
	$(CXX) $(CFLAGS) ../../Compress/Arj/ArjDecoder1.cpp
ArjDecoder2.o : ../../Compress/Arj/ArjDecoder2.cpp
	$(CXX) $(CFLAGS) ../../Compress/Arj/ArjDecoder2.cpp
ByteSwap.o : ../../Compress/ByteSwap/ByteSwap.cpp
	$(CXX) $(CFLAGS) ../../Compress/ByteSwap/ByteSwap.cpp
ByteSwapRegister.o : ../../Compress/ByteSwap/ByteSwapRegister.cpp
	$(CXX) $(CFLAGS) ../../Compress/ByteSwap/ByteSwapRegister.cpp
ShrinkDecoder.o : ../../Compress/Shrink/ShrinkDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Shrink/ShrinkDecoder.cpp
QuantumDecoder.o : ../../Compress/Quantum/QuantumDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Quantum/QuantumDecoder.cpp
LzhDecoder.o : ../../Compress/Lzh/LzhDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Lzh/LzhDecoder.cpp
MyAES.o : ../../Crypto/AES/MyAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/AES/MyAES.cpp
7zAES.o : ../../Crypto/7zAES/7zAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/7zAES.cpp
7zAESRegister.o : ../../Crypto/7zAES/7zAESRegister.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/7zAESRegister.cpp
HmacSha1.o : ../../Crypto/Hash/HmacSha1.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/HmacSha1.cpp
Pbkdf2HmacSha1.o : ../../Crypto/Hash/Pbkdf2HmacSha1.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/Pbkdf2HmacSha1.cpp
RandGen.o : ../../Crypto/Hash/RandGen.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/RandGen.cpp
Sha1.o : ../../Crypto/Hash/Sha1.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/Sha1.cpp
Sha256.o : ../../Crypto/Hash/Sha256.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Hash/Sha256.cpp
RarAES.o : ../../Crypto/RarAES/RarAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/RarAES/RarAES.cpp
Rar20Cipher.o : ../../Crypto/Rar20/Rar20Cipher.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Rar20/Rar20Cipher.cpp
Rar20Crypto.o : ../../Crypto/Rar20/Rar20Crypto.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Rar20/Rar20Crypto.cpp
WzAES.o : ../../Crypto/WzAES/WzAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/WzAES/WzAES.cpp
ZipCipher.o : ../../Crypto/Zip/ZipCipher.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Zip/ZipCipher.cpp
ZipCrypto.o : ../../Crypto/Zip/ZipCrypto.cpp
	$(CXX) $(CFLAGS) ../../Crypto/Zip/ZipCrypto.cpp
CreateCoder.o : ../../Common/CreateCoder.cpp
	$(CXX) $(CFLAGS) ../../Common/CreateCoder.cpp
FilterCoder.o : ../../Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../../Common/FilterCoder.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
InOutTempBuffer.o : ../../Common/InOutTempBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InOutTempBuffer.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
LockedStream.o : ../../Common/LockedStream.cpp
	$(CXX) $(CFLAGS) ../../Common/LockedStream.cpp
LSBFDecoder.o : ../../Common/LSBFDecoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFDecoder.cpp
LSBFEncoder.o : ../../Common/LSBFEncoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFEncoder.cpp
MemBlocks.o : ../../Common/MemBlocks.cpp
	$(CXX) $(CFLAGS) ../../Common/MemBlocks.cpp
MethodId.o : ../../Common/MethodId.cpp
	$(CXX) $(CFLAGS) ../../Common/MethodId.cpp
OffsetStream.o : ../../Common/OffsetStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OffsetStream.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
OutMemStream.o : ../../Common/OutMemStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OutMemStream.cpp
ProgressMt.o : ../../Common/ProgressMt.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressMt.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamBinder.o : ../../Common/StreamBinder.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamBinder.cpp
StreamObjects.o : ../../Common/StreamObjects.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamObjects.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
7zCompressionMode.o : ../../Archive/7z/7zCompressionMode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zCompressionMode.cpp
7zDecode.o : ../../Archive/7z/7zDecode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zDecode.cpp
7zEncode.o : ../../Archive/7z/7zEncode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zEncode.cpp
7zExtract.o : ../../Archive/7z/7zExtract.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zExtract.cpp
7zFolderInStream.o : ../../Archive/7z/7zFolderInStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderInStream.cpp
7zFolderOutStream.o : ../../Archive/7z/7zFolderOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderOutStream.cpp
7zHandler.o : ../../Archive/7z/7zHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandler.cpp
7zHandlerOut.o : ../../Archive/7z/7zHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandlerOut.cpp
7zHeader.o : ../../Archive/7z/7zHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHeader.cpp
7zIn.o : ../../Archive/7z/7zIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zIn.cpp
7zOut.o : ../../Archive/7z/7zOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zOut.cpp
7zProperties.o : ../../Archive/7z/7zProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zProperties.cpp
7zRegister.o : ../../Archive/7z/7zRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zRegister.cpp
7zSpecStream.o : ../../Archive/7z/7zSpecStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zSpecStream.cpp
7zUpdate.o : ../../Archive/7z/7zUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zUpdate.cpp
RarHandler.o : ../../Archive/Rar/RarHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Rar/RarHandler.cpp
RarHeader.o : ../../Archive/Rar/RarHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Rar/RarHeader.cpp
RarIn.o : ../../Archive/Rar/RarIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Rar/RarIn.cpp
RarItem.o : ../../Archive/Rar/RarItem.cpp
	$(CXX) $(CFLAGS) ../../Archive/Rar/RarItem.cpp
RarRegister.o : ../../Archive/Rar/RarRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Rar/RarRegister.cpp
RarVolumeInStream.o : ../../Archive/Rar/RarVolumeInStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Rar/RarVolumeInStream.cpp
ArjHandler.o : ../../Archive/Arj/ArjHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Arj/ArjHandler.cpp
ArjIn.o : ../../Archive/Arj/ArjIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Arj/ArjIn.cpp
ArjRegister.o : ../../Archive/Arj/ArjRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Arj/ArjRegister.cpp
bz2Register.o : ../../Archive/BZip2/bz2Register.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/bz2Register.cpp
BZip2Handler.o : ../../Archive/BZip2/BZip2Handler.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/BZip2Handler.cpp
BZip2HandlerOut.o : ../../Archive/BZip2/BZip2HandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/BZip2HandlerOut.cpp
BZip2Update.o : ../../Archive/BZip2/BZip2Update.cpp
	$(CXX) $(CFLAGS) ../../Archive/BZip2/BZip2Update.cpp
CabBlockInStream.o : ../../Archive/Cab/CabBlockInStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cab/CabBlockInStream.cpp
CabHandler.o : ../../Archive/Cab/CabHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cab/CabHandler.cpp
CabHeader.o : ../../Archive/Cab/CabHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cab/CabHeader.cpp
CabIn.o : ../../Archive/Cab/CabIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cab/CabIn.cpp
CabRegister.o : ../../Archive/Cab/CabRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cab/CabRegister.cpp
ChmHandler.o : ../../Archive/Chm/ChmHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Chm/ChmHandler.cpp
ChmHeader.o : ../../Archive/Chm/ChmHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Chm/ChmHeader.cpp
ChmIn.o : ../../Archive/Chm/ChmIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Chm/ChmIn.cpp
ChmRegister.o : ../../Archive/Chm/ChmRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Chm/ChmRegister.cpp
CoderMixer2.o : ../../Archive/Common/CoderMixer2.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2.cpp
CoderMixer2MT.o : ../../Archive/Common/CoderMixer2MT.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2MT.cpp
CrossThreadProgress.o : ../../Archive/Common/CrossThreadProgress.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CrossThreadProgress.cpp
DummyOutStream.o : ../../Archive/Common/DummyOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/DummyOutStream.cpp
InStreamWithCRC.o : ../../Archive/Common/InStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/InStreamWithCRC.cpp
ItemNameUtils.o : ../../Archive/Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ItemNameUtils.cpp
MultiStream.o : ../../Archive/Common/MultiStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/MultiStream.cpp
OutStreamWithCRC.o : ../../Archive/Common/OutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/OutStreamWithCRC.cpp
ParseProperties.o : ../../Archive/Common/ParseProperties.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ParseProperties.cpp
CpioHandler.o : ../../Archive/Cpio/CpioHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cpio/CpioHandler.cpp
CpioHeader.o : ../../Archive/Cpio/CpioHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cpio/CpioHeader.cpp
CpioIn.o : ../../Archive/Cpio/CpioIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cpio/CpioIn.cpp
CpioRegister.o : ../../Archive/Cpio/CpioRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Cpio/CpioRegister.cpp
DebHandler.o : ../../Archive/Deb/DebHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Deb/DebHandler.cpp
DebHeader.o : ../../Archive/Deb/DebHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Deb/DebHeader.cpp
DebIn.o : ../../Archive/Deb/DebIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Deb/DebIn.cpp
DebRegister.o : ../../Archive/Deb/DebRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Deb/DebRegister.cpp
GZipHandler.o : ../../Archive/GZip/GZipHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipHandler.cpp
GZipHandlerOut.o : ../../Archive/GZip/GZipHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipHandlerOut.cpp
GZipHeader.o : ../../Archive/GZip/GZipHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipHeader.cpp
GZipIn.o : ../../Archive/GZip/GZipIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipIn.cpp
GZipOut.o : ../../Archive/GZip/GZipOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipOut.cpp
GZipRegister.o : ../../Archive/GZip/GZipRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipRegister.cpp
GZipUpdate.o : ../../Archive/GZip/GZipUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/GZip/GZipUpdate.cpp
IsoHandler.o : ../../Archive/Iso/IsoHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Iso/IsoHandler.cpp
IsoHeader.o : ../../Archive/Iso/IsoHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Iso/IsoHeader.cpp
IsoIn.o : ../../Archive/Iso/IsoIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Iso/IsoIn.cpp
IsoRegister.o : ../../Archive/Iso/IsoRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Iso/IsoRegister.cpp
LzhCRC.o : ../../Archive/Lzh/LzhCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Lzh/LzhCRC.cpp
LzhHandler.o : ../../Archive/Lzh/LzhHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Lzh/LzhHandler.cpp
LzhIn.o : ../../Archive/Lzh/LzhIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Lzh/LzhIn.cpp
LzhOutStreamWithCRC.o : ../../Archive/Lzh/LzhOutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Lzh/LzhOutStreamWithCRC.cpp
LzhRegister.o : ../../Archive/Lzh/LzhRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Lzh/LzhRegister.cpp
NsisDecode.o : ../../Archive/Nsis/NsisDecode.cpp
	$(CXX) $(CFLAGS) ../../Archive/Nsis/NsisDecode.cpp
NsisHandler.o : ../../Archive/Nsis/NsisHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Nsis/NsisHandler.cpp
NsisIn.o : ../../Archive/Nsis/NsisIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Nsis/NsisIn.cpp
NsisRegister.o : ../../Archive/Nsis/NsisRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Nsis/NsisRegister.cpp
RpmHandler.o : ../../Archive/RPM/RpmHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/RPM/RpmHandler.cpp
RpmIn.o : ../../Archive/RPM/RpmIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/RPM/RpmIn.cpp
RpmRegister.o : ../../Archive/RPM/RpmRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/RPM/RpmRegister.cpp
SplitHandler.o : ../../Archive/Split/SplitHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Split/SplitHandler.cpp
SplitHandlerOut.o : ../../Archive/Split/SplitHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Split/SplitHandlerOut.cpp
SplitRegister.o : ../../Archive/Split/SplitRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Split/SplitRegister.cpp
TarHandler.o : ../../Archive/Tar/TarHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarHandler.cpp
TarHandlerOut.o : ../../Archive/Tar/TarHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarHandlerOut.cpp
TarHeader.o : ../../Archive/Tar/TarHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarHeader.cpp
TarIn.o : ../../Archive/Tar/TarIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarIn.cpp
TarOut.o : ../../Archive/Tar/TarOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarOut.cpp
TarRegister.o : ../../Archive/Tar/TarRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarRegister.cpp
TarUpdate.o : ../../Archive/Tar/TarUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/Tar/TarUpdate.cpp
ZHandler.o : ../../Archive/Z/ZHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Z/ZHandler.cpp
ZRegister.o : ../../Archive/Z/ZRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Z/ZRegister.cpp
ZipAddCommon.o : ../../Archive/Zip/ZipAddCommon.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipAddCommon.cpp
ZipHandler.o : ../../Archive/Zip/ZipHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipHandler.cpp
ZipHandlerOut.o : ../../Archive/Zip/ZipHandlerOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipHandlerOut.cpp
ZipHeader.o : ../../Archive/Zip/ZipHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipHeader.cpp
ZipIn.o : ../../Archive/Zip/ZipIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipIn.cpp
ZipItem.o : ../../Archive/Zip/ZipItem.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipItem.cpp
ZipOut.o : ../../Archive/Zip/ZipOut.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipOut.cpp
ZipRegister.o : ../../Archive/Zip/ZipRegister.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipRegister.cpp
ZipUpdate.o : ../../Archive/Zip/ZipUpdate.cpp
	$(CXX) $(CFLAGS) ../../Archive/Zip/ZipUpdate.cpp
aescrypt.o : ../../Crypto/AES/aescrypt.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aescrypt.c
aeskey.o : ../../Crypto/AES/aeskey.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aeskey.c
aestab.o : ../../Crypto/AES/aestab.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aestab.c
MatchFinder.o : ../../../../C/Compress/Lz/MatchFinder.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Lz/MatchFinder.c
MatchFinderMt.o : ../../../../C/Compress/Lz/MatchFinderMt.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Lz/MatchFinderMt.c
HuffmanEncode.o : ../../../../C/Compress/Huffman/HuffmanEncode.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Huffman/HuffmanEncode.c
BranchARM.o : ../../../../C/Compress/Branch/BranchARM.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Branch/BranchARM.c
BranchARMThumb.o : ../../../../C/Compress/Branch/BranchARMThumb.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Branch/BranchARMThumb.c
BranchIA64.o : ../../../../C/Compress/Branch/BranchIA64.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Branch/BranchIA64.c
BranchPPC.o : ../../../../C/Compress/Branch/BranchPPC.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Branch/BranchPPC.c
BranchSPARC.o : ../../../../C/Compress/Branch/BranchSPARC.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Branch/BranchSPARC.c
BranchX86.o : ../../../../C/Compress/Branch/BranchX86.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Branch/BranchX86.c
Sort.o : ../../../../C/Sort.c
	$(CC) $(CFLAGS) ../../../../C/Sort.c
Threads.o : ../../../../C/Threads.c
	$(CC) $(CFLAGS) ../../../../C/Threads.c

