SRCS=\
./DllExports.cpp \
./NsisDecode.cpp \
./NsisHandler.cpp \
./NsisIn.cpp \
 ../../../Windows/DLL.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamUtils.cpp \
 ../Common/CodecsPath.cpp \
 ../Common/CoderLoader.cpp \
 ../Common/ItemNameUtils.cpp \
 ../Common/FilterCoder.cpp \
 ../7z/7zMethodID.cpp \
 ../7z/7zMethods.cpp \

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
NsisDecode.o : ./NsisDecode.cpp
	$(CXX) $(CFLAGS) ./NsisDecode.cpp
NsisHandler.o : ./NsisHandler.cpp
	$(CXX) $(CFLAGS) ./NsisHandler.cpp
NsisIn.o : ./NsisIn.cpp
	$(CXX) $(CFLAGS) ./NsisIn.cpp
DLL.o : ../../../Windows/DLL.cpp
	$(CXX) $(CFLAGS) ../../../Windows/DLL.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
CodecsPath.o : ../Common/CodecsPath.cpp
	$(CXX) $(CFLAGS) ../Common/CodecsPath.cpp
CoderLoader.o : ../Common/CoderLoader.cpp
	$(CXX) $(CFLAGS) ../Common/CoderLoader.cpp
ItemNameUtils.o : ../Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../Common/ItemNameUtils.cpp
FilterCoder.o : ../Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../Common/FilterCoder.cpp
7zMethodID.o : ../7z/7zMethodID.cpp
	$(CXX) $(CFLAGS) ../7z/7zMethodID.cpp
7zMethods.o : ../7z/7zMethods.cpp
	$(CXX) $(CFLAGS) ../7z/7zMethods.cpp
