SRCS=\
 ../../../myWindows/wine_date_and_time.cpp \
 ../../../myWindows/myAddExeFlag.cpp \
 ../../../myWindows/mySplitCommandLine.cpp \
 ../../../Common/CommandLineParser.cpp \
 ../../../Common/CRC.cpp \
 ../../../Common/IntToString.cpp \
 ../../../Common/ListFileUtils.cpp \
 ../../../Common/MyWindows.cpp \
 ../../../Common/StdInStream.cpp \
 ../../../Common/StdOutStream.cpp \
 ../../../Common/MyString.cpp \
 ../../../Common/StringConvert.cpp \
 ../../../Common/StringToInt.cpp \
 ../../../Common/UTFConvert.cpp \
 ../../../Common/MyVector.cpp \
 ../../../Common/Wildcard.cpp \
 ../Common/ArchiveCommandLine.cpp \
 ../Common/ArchiveExtractCallback.cpp \
 ../Common/ArchiveOpenCallback.cpp \
 ../Common/DefaultName.cpp \
 ../Common/EnumDirItems.cpp \
 ../Common/Extract.cpp \
 ../Common/ExtractingFilePath.cpp \
 ../../Common/FilePathAutoRename.cpp \
 ../../Common/FileStreams.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamUtils.cpp \
 ../Common/OpenArchive.cpp \
 ../Common/LoadCodecs.cpp \
 ../Common/PropIDUtils.cpp \
 ../Common/SetProperties.cpp \
 ../Common/SortUtils.cpp \
 ../Common/TempFiles.cpp \
 ../Common/UpdateAction.cpp \
 ../Common/UpdateCallback.cpp \
 ../Common/Update.cpp \
 ../Common/UpdatePair.cpp \
 ../Common/UpdateProduce.cpp \
 ../../Compress/Copy/CopyCoder.cpp \
 ../../Compress/LZMA_Alone/LzmaBench.cpp \
 ../../Compress/LZMA_Alone/LzmaBenchCon.cpp \
 ./ConsoleClose.cpp \
 ./ExtractCallbackConsole.cpp \
 ./List.cpp \
 ./MainAr.cpp \
 ./Main.cpp \
 ./OpenCallbackConsole.cpp \
 ./PercentPrinter.cpp \
 ./UpdateCallbackConsole.cpp \
 ./UserInputUtils.cpp \
 ../../../Windows/DLL.cpp \
 ../../../Windows/Error.cpp \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/FileName.cpp \
 ../../../Windows/PropVariantConversions.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/Time.cpp \
 ../../../Windows/System.cpp

SRCS_C=\
 ../../../../C/7zCrc.c \
 ../../../../C/Threads.c

wine_date_and_time.o : ../../../myWindows/wine_date_and_time.cpp
	$(CXX) $(CFLAGS) ../../../myWindows/wine_date_and_time.cpp
myAddExeFlag.o : ../../../myWindows/myAddExeFlag.cpp
	$(CXX) $(CFLAGS) ../../../myWindows/myAddExeFlag.cpp 
mySplitCommandLine.o : ../../../myWindows/mySplitCommandLine.cpp
	$(CXX) $(CFLAGS) ../../../myWindows/mySplitCommandLine.cpp
CommandLineParser.o : ../../../Common/CommandLineParser.cpp
	$(CXX) $(CFLAGS) ../../../Common/CommandLineParser.cpp
CRC.o : ../../../Common/CRC.cpp
	$(CXX) $(CFLAGS) ../../../Common/CRC.cpp
IntToString.o : ../../../Common/IntToString.cpp
	$(CXX) $(CFLAGS) ../../../Common/IntToString.cpp
ListFileUtils.o : ../../../Common/ListFileUtils.cpp
	$(CXX) $(CFLAGS) ../../../Common/ListFileUtils.cpp
MyWindows.o : ../../../Common/MyWindows.cpp
	$(CXX) $(CFLAGS) ../../../Common/MyWindows.cpp
Random.o : ../../../Common/Random.cpp
	$(CXX) $(CFLAGS) ../../../Common/Random.cpp
StdInStream.o : ../../../Common/StdInStream.cpp
	$(CXX) $(CFLAGS) ../../../Common/StdInStream.cpp
StdOutStream.o : ../../../Common/StdOutStream.cpp
	$(CXX) $(CFLAGS) ../../../Common/StdOutStream.cpp
MyString.o : ../../../Common/MyString.cpp
	$(CXX) $(CFLAGS) ../../../Common/MyString.cpp
StringConvert.o : ../../../Common/StringConvert.cpp
	$(CXX) $(CFLAGS) ../../../Common/StringConvert.cpp
StringToInt.o : ../../../Common/StringToInt.cpp
	$(CXX) $(CFLAGS) ../../../Common/StringToInt.cpp
UTFConvert.o : ../../../Common/UTFConvert.cpp
	$(CXX) $(CFLAGS) ../../../Common/UTFConvert.cpp
MyVector.o : ../../../Common/MyVector.cpp
	$(CXX) $(CFLAGS) ../../../Common/MyVector.cpp
Wildcard.o : ../../../Common/Wildcard.cpp
	$(CXX) $(CFLAGS) ../../../Common/Wildcard.cpp

ConsoleClose.o : ./ConsoleClose.cpp
	$(CXX) $(CFLAGS) ./ConsoleClose.cpp
ExtractCallbackConsole.o : ./ExtractCallbackConsole.cpp
	$(CXX) $(CFLAGS) ./ExtractCallbackConsole.cpp
List.o : ./List.cpp
	$(CXX) $(CFLAGS) ./List.cpp
Main.o : ./Main.cpp
	$(CXX) $(CFLAGS) ./Main.cpp
MainAr.o : ./MainAr.cpp
	$(CXX) $(CFLAGS) ./MainAr.cpp
OpenCallbackConsole.o : ./OpenCallbackConsole.cpp
	$(CXX) $(CFLAGS) ./OpenCallbackConsole.cpp
PercentPrinter.o : ./PercentPrinter.cpp
	$(CXX) $(CFLAGS) ./PercentPrinter.cpp
UpdateCallbackConsole.o : ./UpdateCallbackConsole.cpp
	$(CXX) $(CFLAGS) ./UpdateCallbackConsole.cpp
UserInputUtils.o : ./UserInputUtils.cpp
	$(CXX) $(CFLAGS) ./UserInputUtils.cpp
DLL.o : ../../../Windows/DLL.cpp
	$(CXX) $(CFLAGS) ../../../Windows/DLL.cpp
Error.o : ../../../Windows/Error.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Error.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariantConversions.cpp
Time.o : ../../../Windows/Time.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Time.cpp
System.o : ../../../Windows/System.cpp
	$(CXX) $(CFLAGS) ../../../Windows/System.cpp
ArchiveCommandLine.o : ../Common/ArchiveCommandLine.cpp
	$(CXX) $(CFLAGS) ../Common/ArchiveCommandLine.cpp
ArchiveExtractCallback.o : ../Common/ArchiveExtractCallback.cpp
	$(CXX) $(CFLAGS) ../Common/ArchiveExtractCallback.cpp
ArchiveOpenCallback.o : ../Common/ArchiveOpenCallback.cpp
	$(CXX) $(CFLAGS) ../Common/ArchiveOpenCallback.cpp
DefaultName.o : ../Common/DefaultName.cpp
	$(CXX) $(CFLAGS) ../Common/DefaultName.cpp
EnumDirItems.o : ../Common/EnumDirItems.cpp
	$(CXX) $(CFLAGS) ../Common/EnumDirItems.cpp
Extract.o : ../Common/Extract.cpp
	$(CXX) $(CFLAGS) ../Common/Extract.cpp
SetProperties.o : ../Common/SetProperties.cpp
	$(CXX) $(CFLAGS) ../Common/SetProperties.cpp
ExtractingFilePath.o : ../Common/ExtractingFilePath.cpp
	$(CXX) $(CFLAGS) ../Common/ExtractingFilePath.cpp
OpenArchive.o : ../Common/OpenArchive.cpp
	$(CXX) $(CFLAGS) ../Common/OpenArchive.cpp
LoadCodecs.o : ../Common/LoadCodecs.cpp
	$(CXX) $(CFLAGS) ../Common/LoadCodecs.cpp
PropIDUtils.o : ../Common/PropIDUtils.cpp
	$(CXX) $(CFLAGS) ../Common/PropIDUtils.cpp
SortUtils.o : ../Common/SortUtils.cpp
	$(CXX) $(CFLAGS) ../Common/SortUtils.cpp
TempFiles.o : ../Common/TempFiles.cpp
	$(CXX) $(CFLAGS) ../Common/TempFiles.cpp
Update.o : ../Common/Update.cpp
	$(CXX) $(CFLAGS) ../Common/Update.cpp
UpdateAction.o : ../Common/UpdateAction.cpp
	$(CXX) $(CFLAGS) ../Common/UpdateAction.cpp
UpdateCallback.o : ../Common/UpdateCallback.cpp
	$(CXX) $(CFLAGS) ../Common/UpdateCallback.cpp
UpdatePair.o : ../Common/UpdatePair.cpp
	$(CXX) $(CFLAGS) ../Common/UpdatePair.cpp
UpdateProduce.o : ../Common/UpdateProduce.cpp
	$(CXX) $(CFLAGS) ../Common/UpdateProduce.cpp
FilePathAutoRename.o : ../../Common/FilePathAutoRename.cpp
	$(CXX) $(CFLAGS) ../../Common/FilePathAutoRename.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/FileStreams.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
LzmaBench.o : ../../Compress/LZMA_Alone/LzmaBench.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA_Alone/LzmaBench.cpp
LzmaBenchCon.o : ../../Compress/LZMA_Alone/LzmaBenchCon.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA_Alone/LzmaBenchCon.cpp
Threads.o : ../../../../C/Threads.c
	$(CC) $(CFLAGS) ../../../../C/Threads.c
# CRC32, C version
7zCrc.o : ../../../../C/7zCrc.c
	$(CC) $(CC_SHARED) $(CFLAGS) ../../../../C/7zCrc.c
# CRC32, ASM version
7zCrcT8.o : ../../../../C/7zCrcT8.c
	$(CC) $(CC_SHARED) $(CFLAGS) ../../../../C/7zCrcT8.c
