SRCS=\
../../Common/LimitedStreams.cpp \
../../Common/StreamUtils.cpp \
../../Common/ProgressUtils.cpp \
../Common/ItemNameUtils.cpp \
./DllExports.cpp \
./IsoHandler.cpp \
./IsoHeader.cpp \
./IsoIn.cpp \
../../../Windows/PropVariant.cpp \
../../Compress/Copy/CopyCoder.cpp

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
IsoHandler.o : ./IsoHandler.cpp
	$(CXX) $(CFLAGS) ./IsoHandler.cpp
IsoHeader.o : ./IsoHeader.cpp
	$(CXX) $(CFLAGS) ./IsoHeader.cpp
IsoIn.o : ./IsoIn.cpp
	$(CXX) $(CFLAGS) ./IsoIn.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
ItemNameUtils.o : ../Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../Common/ItemNameUtils.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp

