PROG=common

LOCAL_FLAGS=-DENV_UNIX -I../myWindows -I../ -I../include_windows

include ../makefile.machine

LOCAL_SHARED=

OBJS=\
main.o \
StringToInt.o \
Vector.o \
AlignedBuffer.o \
Alloc.o \
CommandLineParser.o \
CRC.o \
IntToString.o \
ListFileUtils.o \
MyWindows.o \
Random.o \
StdInStream.o \
StdOutStream.o \
StringConvert.o \
String.o \
UTFConvert.o \
Wildcard.o

include ../makefile.glb

