SRCS=\
 ../../Archive/7z/7zDecode.cpp \
 ../../Archive/7z/7zExtract.cpp \
 ../../Archive/7z/7zFolderOutStream.cpp \
 ../../Archive/7z/7zHandler.cpp \
 ../../Archive/7z/7zHeader.cpp \
 ../../Archive/7z/7zIn.cpp \
 ../../Archive/7z/7zMethodID.cpp \
 ../../Archive/Common/CoderMixer2.cpp \
 ../../Archive/Common/CoderMixer2MT.cpp \
 ../../Archive/Common/CoderMixer2ST.cpp \
 ../../Archive/Common/CrossThreadProgress.cpp \
 ../../Archive/Common/FilterCoder.cpp \
 ../../Archive/Common/ItemNameUtils.cpp \
 ../../Archive/Common/OutStreamWithCRC.cpp \
 ../../Common/FilePathAutoRename.cpp \
 ../../Common/FileStreams.cpp \
 ../../Common/InBuffer.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/LockedStream.cpp \
 ../../Common/OffsetStream.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamBinder.cpp \
 ../../Common/StreamObjects.cpp \
 ../../Compress/Branch/BranchCoder.cpp \
 ../../Compress/Branch/x86_2.cpp \
 ../../Compress/Branch/x86.cpp \
 ../../Compress/Copy/CopyCoder.cpp \
 ../../Compress/LZ/LZOutWindow.cpp \
 ../../Compress/LZMA/LZMADecoder.cpp \
 ../../Compress/PPMD/PPMDDecoder.cpp \
 ../../Crypto/7zAES/7zAES.cpp \
 ../../Crypto/7zAES/SHA256.cpp \
 ../../Crypto/AES/MyAES.cpp \
 ./Main.cpp \
 ../../UI/Common/ArchiveExtractCallback.cpp \
 ../../UI/Common/ArchiveOpenCallback.cpp \
 ../../UI/Common/ArchiverInfo.cpp \
 ../../UI/Common/DefaultName.cpp \
 ../../UI/Common/Extract.cpp \
 ../../UI/Common/ExtractingFilePath.cpp \
 ../../UI/Common/OpenArchive.cpp \
 ../../UI/Common/PropIDUtils.cpp \
 ../../UI/Console/ConsoleClose.cpp \
 ../../UI/Console/ExtractCallbackConsole.cpp \
 ../../UI/Console/List.cpp \
 ../../UI/Console/MainAr.cpp \
 ../../UI/Console/OpenCallbackConsole.cpp \
 ../../UI/Console/UserInputUtils.cpp \
 ../../../Windows/Error.cpp \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/FileName.cpp \
 ../../../Windows/PropVariantConversions.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/Synchronization.cpp

SRCS_C=\
 ../../Crypto/AES/aescrypt.c \
 ../../Crypto/AES/aeskey.c \
 ../../Crypto/AES/aestab.c

CoderMixer2.o : ../../Archive/Common/CoderMixer2.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2.cpp
CoderMixer2MT.o : ../../Archive/Common/CoderMixer2MT.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2MT.cpp
CoderMixer2ST.o : ../../Archive/Common/CoderMixer2ST.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CoderMixer2ST.cpp
CrossThreadProgress.o : ../../Archive/Common/CrossThreadProgress.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/CrossThreadProgress.cpp
FilterCoder.o : ../../Archive/Common/FilterCoder.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/FilterCoder.cpp
ItemNameUtils.o : ../../Archive/Common/ItemNameUtils.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/ItemNameUtils.cpp
OutStreamWithCRC.o : ../../Archive/Common/OutStreamWithCRC.cpp
	$(CXX) $(CFLAGS) ../../Archive/Common/OutStreamWithCRC.cpp
ConsoleClose.o : ../../UI/Console/ConsoleClose.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/ConsoleClose.cpp
ExtractCallbackConsole.o : ../../UI/Console/ExtractCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/ExtractCallbackConsole.cpp
List.o : ../../UI/Console/List.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/List.cpp
MainAr.o : ../../UI/Console/MainAr.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/MainAr.cpp
OpenCallbackConsole.o : ../../UI/Console/OpenCallbackConsole.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/OpenCallbackConsole.cpp
UserInputUtils.o : ../../UI/Console/UserInputUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Console/UserInputUtils.cpp
7zDecode.o : ../../Archive/7z/7zDecode.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zDecode.cpp
7zExtract.o : ../../Archive/7z/7zExtract.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zExtract.cpp
7zFolderOutStream.o : ../../Archive/7z/7zFolderOutStream.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zFolderOutStream.cpp
7zHandler.o : ../../Archive/7z/7zHandler.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHandler.cpp
7zHeader.o : ../../Archive/7z/7zHeader.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zHeader.cpp
7zIn.o : ../../Archive/7z/7zIn.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zIn.cpp
7zMethodID.o : ../../Archive/7z/7zMethodID.cpp
	$(CXX) $(CFLAGS) ../../Archive/7z/7zMethodID.cpp
LZMADecoder.o : ../../Compress/LZMA/LZMADecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZMA/LZMADecoder.cpp
BranchCoder.o : ../../Compress/Branch/BranchCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/BranchCoder.cpp
x86.o : ../../Compress/Branch/x86.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86.cpp
x86_2.o : ../../Compress/Branch/x86_2.cpp
	$(CXX) $(CFLAGS) ../../Compress/Branch/x86_2.cpp
PPMDDecoder.o : ../../Compress/PPMD/PPMDDecoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/PPMD/PPMDDecoder.cpp
LZOutWindow.o : ../../Compress/LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../../Compress/LZ/LZOutWindow.cpp
CopyCoder.o : ../../Compress/Copy/CopyCoder.cpp
	$(CXX) $(CFLAGS) ../../Compress/Copy/CopyCoder.cpp
7zAES.o : ../../Crypto/7zAES/7zAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/7zAES.cpp
SHA256.o : ../../Crypto/7zAES/SHA256.cpp
	$(CXX) $(CFLAGS) ../../Crypto/7zAES/SHA256.cpp
MyAES.o : ../../Crypto/AES/MyAES.cpp
	$(CXX) $(CFLAGS) ../../Crypto/AES/MyAES.cpp
Error.o : ../../../Windows/Error.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Error.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CFLAGS) ../../../Windows/PropVariantConversions.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CFLAGS) ../../../Windows/Synchronization.cpp
FilePathAutoRename.o : ../../Common/FilePathAutoRename.cpp
	$(CXX) $(CFLAGS) ../../Common/FilePathAutoRename.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/FileStreams.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
LimitedStreams.o : ../../Common/LimitedStreams.cpp
	$(CXX) $(CFLAGS) ../../Common/LimitedStreams.cpp
LockedStream.o : ../../Common/LockedStream.cpp
	$(CXX) $(CFLAGS) ../../Common/LockedStream.cpp
OffsetStream.o : ../../Common/OffsetStream.cpp
	$(CXX) $(CFLAGS) ../../Common/OffsetStream.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/ProgressUtils.cpp
StreamBinder.o : ../../Common/StreamBinder.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamBinder.cpp
StreamObjects.o : ../../Common/StreamObjects.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamObjects.cpp
ArchiveExtractCallback.o : ../../UI/Common/ArchiveExtractCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveExtractCallback.cpp
ArchiveOpenCallback.o : ../../UI/Common/ArchiveOpenCallback.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiveOpenCallback.cpp
ArchiverInfo.o : ../../UI/Common/ArchiverInfo.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ArchiverInfo.cpp
DefaultName.o : ../../UI/Common/DefaultName.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/DefaultName.cpp
Extract.o : ../../UI/Common/Extract.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/Extract.cpp
ExtractingFilePath.o : ../../UI/Common/ExtractingFilePath.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/ExtractingFilePath.cpp
OpenArchive.o : ../../UI/Common/OpenArchive.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/OpenArchive.cpp
PropIDUtils.o : ../../UI/Common/PropIDUtils.cpp
	$(CXX) $(CFLAGS) ../../UI/Common/PropIDUtils.cpp
Main.o : ./Main.cpp
	$(CXX) $(CFLAGS) ./Main.cpp
aescrypt.o : ../../Crypto/AES/aescrypt.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aescrypt.c
aeskey.o : ../../Crypto/AES/aeskey.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aeskey.c
aestab.o : ../../Crypto/AES/aestab.c
	$(CC) $(CFLAGS) ../../Crypto/AES/aestab.c
