PROG=../../../bin/Codecs/Swap.so

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)
LIBS=$(LOCAL_LIBS)

OBJS = \
../../../Common/MyWindows.o \
DllExports.o \
ByteSwap.o

include ../../../makefile.glb

