SRCS=\
 ../../Common/InBuffer.cpp \
 ../../Common/LSBFDecoder.cpp \
 ../../Common/LSBFEncoder.cpp \
 ../../Common/OutBuffer.cpp \
 ./DeflateDecoder.cpp \
 ./DeflateEncoder.cpp \
 ./DllExports.cpp \
 ../LZ/LZOutWindow.cpp \
 ../../../../C/7zCrc.c \
 ../../../../C/Sort.c \
 ../../../../C/Compress/Lz/MatchFinder.c \
 ../../../../C/Compress/Huffman/HuffmanEncode.c

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
LSBFDecoder.o : ../../Common/LSBFDecoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFDecoder.cpp
LSBFEncoder.o : ../../Common/LSBFEncoder.cpp
	$(CXX) $(CFLAGS) ../../Common/LSBFEncoder.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
LZOutWindow.o : ../LZ/LZOutWindow.cpp
	$(CXX) $(CFLAGS) ../LZ/LZOutWindow.cpp
DeflateDecoder.o : ./DeflateDecoder.cpp
	$(CXX) $(CFLAGS) ./DeflateDecoder.cpp
DeflateEncoder.o : ./DeflateEncoder.cpp
	$(CXX) $(CFLAGS) ./DeflateEncoder.cpp
7zCrc.o : ../../../../C/7zCrc.c
	$(CC) $(CFLAGS) ../../../../C/7zCrc.c
Sort.o : ../../../../C/Sort.c
	$(CC) $(CFLAGS) ../../../../C/Sort.c
MatchFinder.o : ../../../../C/Compress/Lz/MatchFinder.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Lz/MatchFinder.c
HuffmanEncode.o : ../../../../C/Compress/Huffman/HuffmanEncode.c
	$(CC) $(CFLAGS) ../../../../C/Compress/Huffman/HuffmanEncode.c
