SRCS=\
 ../../Common/InBuffer.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/StreamUtils.cpp \
 ./DllExports.cpp \
 ./PPMDDecoder.cpp \
 ./PPMDEncoder.cpp

DllExports.o : ./DllExports.cpp
	$(CXX) $(CFLAGS) ./DllExports.cpp
PPMDDecoder.o : ./PPMDDecoder.cpp
	$(CXX) $(CFLAGS) ./PPMDDecoder.cpp
PPMDEncoder.o : ./PPMDEncoder.cpp
	$(CXX) $(CFLAGS) ./PPMDEncoder.cpp
InBuffer.o : ../../Common/InBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/InBuffer.cpp
OutBuffer.o : ../../Common/OutBuffer.cpp
	$(CXX) $(CFLAGS) ../../Common/OutBuffer.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CFLAGS) ../../Common/StreamUtils.cpp
